import { readFileSync, writeFileSync, mkdirSync, statSync, readdirSync } from 'node:fs';
import { resolve, relative, dirname, join, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * Generate `src/generated/assets.ts` — an embedded copy of every data file under
 * agents/, reference/, and skills/. This is what makes the app deployable to a
 * serverless target (Vercel): the Mastra bundler only bundles JS reachable via
 * static import, so the .md / skill files we read with `fs` at runtime would
 * otherwise be missing. At cold start we materialize this map to a writable temp
 * dir (see src/lib/loadPrompt.ts) and everything reads from there exactly as it
 * does locally.
 *
 * Run via `npm run generate:assets` (also wired into `npm run build`).
 */

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
const DIRS = ['agents', 'reference', 'skills'];
const OUT = resolve(ROOT, 'src', 'generated', 'assets.ts');

function walk(dir: string, acc: string[]): string[] {
  for (const name of readdirSync(dir)) {
    const abs = join(dir, name);
    const st = statSync(abs);
    if (st.isDirectory()) walk(abs, acc);
    else acc.push(abs);
  }
  return acc;
}

function main(): void {
  const map: Record<string, string> = {};
  let bytes = 0;
  for (const d of DIRS) {
    const base = resolve(ROOT, d);
    let files: string[] = [];
    try {
      files = walk(base, []);
    } catch {
      console.warn(`[embed-assets] skipping missing dir: ${d}`);
      continue;
    }
    for (const abs of files) {
      // POSIX-style repo-relative key so it matches loadMarkdownBody() relPaths.
      const rel = relative(ROOT, abs).split(sep).join('/');
      const content = readFileSync(abs, 'utf8');
      map[rel] = content;
      bytes += content.length;
    }
  }

  const keys = Object.keys(map).sort();
  const sorted: Record<string, string> = {};
  for (const k of keys) sorted[k] = map[k];

  const banner =
    '// AUTO-GENERATED by src/scripts/embedAssets.ts — do not edit by hand.\n' +
    `// Embeds ${keys.length} data files (${(bytes / 1024).toFixed(0)} KB) so the app\n` +
    '// can run on a serverless target without the source tree on disk.\n';
  const body = `export const EMBEDDED_ASSETS: Record<string, string> = ${JSON.stringify(sorted, null, 0)};\n`;

  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, banner + body);
  console.log(`[embed-assets] wrote ${keys.length} files (${(bytes / 1024).toFixed(0)} KB) -> ${relative(ROOT, OUT)}`);
}

main();
