export {}; // module (top-level await)

/**
 * Head-to-head: GLM-5.2 (current main) vs Kimi K2.7-Code (coding-tuned, same price) on the
 * copilot's coding-shaped tasks — function authoring, transcript diagnosis, code debugging.
 * Each task is generated by both models, then judged pairwise by a NEUTRAL model (Qwen3.7
 * Plus) with randomized A/B order to avoid position bias. Outputs are printed so a human
 * (Claude) can also judge. Tells us whether to route specific roles to Kimi.
 *
 * Run: GLM_API_KEY=… npx tsx src/scripts/modelAbTest.ts
 */
const KEY = process.env.GLM_API_KEY ?? '';
const BASE = process.env.GLM_BASE_URL ?? 'https://api.fireworks.ai/inference/v1';
if (!KEY) { console.error('GLM_API_KEY required'); process.exit(1); }

const GLM = 'accounts/fireworks/models/glm-5p2';
const KIMI = 'accounts/fireworks/models/kimi-k2p7-code';
const JUDGE = 'accounts/fireworks/models/qwen3p7-plus';

async function gen(model: string, system: string, user: string, maxTokens = 2500): Promise<string> {
  try {
    const r = await fetch(`${BASE}/chat/completions`, {
      method: 'POST',
      headers: { authorization: `Bearer ${KEY}`, 'content-type': 'application/json' },
      body: JSON.stringify({ model, max_tokens: maxTokens, temperature: 0.2, messages: [{ role: 'system', content: system }, { role: 'user', content: user }] }),
    });
    const j: any = await r.json();
    const m = j?.choices?.[0]?.message ?? {};
    return (m.content ?? '') || `(no content; err: ${JSON.stringify(j?.error ?? j).slice(0, 200)})`;
  } catch (e: any) { return `(fetch error: ${e?.message})`; }
}

const TASKS = [
  {
    id: 'function-authoring',
    system: 'You are an expert Voiceflow Function developer. Voiceflow Functions export `async function main(args)`; input variables are on `args.inputVars`; you return `{ outputVars, next: { path }, trace }`. Write complete, production-quality JavaScript — no placeholders, no TODOs.',
    user: 'Write the function. Inputs: `orderId` (string), `apiKey` (string). Call GET https://api.shop.example/orders/{orderId} with header `Authorization: Bearer {apiKey}`. On success set outputVars `orderStatus` and `estimatedDelivery` from the JSON and `next.path = "success"`. Robustly handle: missing/empty orderId, non-2xx responses, network/timeout errors, and malformed JSON — on any failure set outputVar `errorMessage` and `next.path = "error"`. Use a fetch timeout.',
  },
  {
    id: 'transcript-diagnosis',
    system: 'You are a senior Voiceflow debugging expert. Diagnose precisely; cite the turn.',
    user: 'Transcript:\n1 user: I want to book a demo\n2 assistant: Sure! What is your email?\n3 user: jane@acme.com\n4 assistant: Great — what is your email so I can send the invite?\n5 user: I just gave it: jane@acme.com\n6 assistant: Thanks! What is your email?\n\nThe agent keeps re-asking for the email it already received. Diagnose the root cause and give the exact fix. Respond ONLY JSON: {"summary":"","rootCauseCategory":"prompt|tool|wiring|context|edge_case|other","problemTurn":0,"evidence":"","fix":"","confidence":"low|medium|high"}.',
  },
  {
    id: 'code-debugging',
    system: 'You are an expert JavaScript debugger.',
    user: 'This Voiceflow Function returns `temp` as undefined every time. Find the bug, explain it briefly, and give the corrected code:\n\nasync function main(args) {\n  const { city } = args.inputVars;\n  let weather;\n  fetch(`https://api.weather.example/${city}`)\n    .then(r => r.json())\n    .then(d => { weather = d.temp; });\n  return { outputVars: { temp: weather }, next: { path: "done" } };\n}',
  },
];

const tally: Record<string, number> = { GLM: 0, KIMI: 0, tie: 0 };

for (const t of TASKS) {
  console.log(`\n${'='.repeat(72)}\nTASK: ${t.id}\n${'='.repeat(72)}`);
  const [glmOut, kimiOut] = await Promise.all([gen(GLM, t.system, t.user), gen(KIMI, t.system, t.user)]);
  console.log(`\n----- GLM-5.2 -----\n${glmOut.slice(0, 2000)}`);
  console.log(`\n----- KIMI-K2.7-CODE -----\n${kimiOut.slice(0, 2000)}`);

  const flip = Math.random() < 0.5;
  const A = flip ? kimiOut : glmOut, B = flip ? glmOut : kimiOut;
  const aModel = flip ? 'KIMI' : 'GLM', bModel = flip ? 'GLM' : 'KIMI';
  const jr = await gen(
    JUDGE,
    'You are an impartial senior engineer judging two solutions to the same task on correctness, robustness, and completeness. Be decisive.',
    `TASK:\n${t.user}\n\n=== Response A ===\n${A}\n\n=== Response B ===\n${B}\n\nWhich response is better? Respond ONLY JSON {"winner":"A"|"B"|"tie","reason":"one sentence"}.`,
    1000,
  );
  const wm = jr.match(/"winner"\s*:\s*"(A|B|tie)"/i);
  const winner = wm ? (/tie/i.test(wm[1]) ? 'tie' : (wm[1].toUpperCase() === 'A' ? aModel : bModel)) : '?';
  if (winner in tally) tally[winner]++;
  const reason = jr.match(/"reason"\s*:\s*"([^"]*)"/)?.[1] ?? jr.slice(0, 160);
  console.log(`\n>>> NEUTRAL JUDGE (Qwen3.7): winner=${winner}  [A=${aModel} B=${bModel}]\n    ${reason.slice(0, 200)}`);
}

console.log(`\n${'='.repeat(72)}\nNEUTRAL-JUDGE TALLY:  GLM=${tally.GLM}  KIMI=${tally.KIMI}  tie=${tally.tie}`);
process.exit(0);
